# Generated by Django 4.2.5 on 2023-10-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_file', models.FileField(upload_to='static/upload')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='static/results')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/upload')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='main.order')),
            ],
        ),
    ]
