# Generated by Django 4.2.5 on 2023-10-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_result_file_resultfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='face',
            field=models.FileField(blank=True, null=True, upload_to='static/upload'),
        ),
    ]
