# Generated by Django 4.2.5 on 2023-10-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sourcefile_trimmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='static/upload'),
        ),
    ]
