# Generated by Django 4.2.5 on 2023-10-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sourcefile_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='preview_deepfaked',
            field=models.FileField(blank=True, null=True, upload_to='static/upload'),
        ),
    ]
