# Generated by Django 4.2.5 on 2023-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sourcefile_preview_deepfaked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='target_face',
            field=models.FileField(blank=True, null=True, upload_to='static/upload'),
        ),
    ]
