# Generated by Django 4.2.5 on 2023-10-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_target_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='main.order'),
        ),
    ]
